image: docker:git
services:
- docker:dind

stages:
- build
- test
- deploy

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/reocoker1985/restful-api/hello:gitlab-$CI_COMMIT_SHORT_SHA
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/reocoker1985/restful-api/python-api:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  tags:
    - linux
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

deploy:
  stage: deploy
  tags:
    - linux
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - main
