version: "3.7"
services:
  gitlab-runner1:
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab-runner1
    volumes:
     - /srv/gitlab-runner/gitlab-runner:/etc/gitlab-runner
     - /var/run/docker.sock:/var/run/docker.sock
    ports:
     - "8093:8093"
