---
- name: Preapre all hosts
  hosts: all
  tasks:
    - name: Create group
      become: true
      ansible.builtin.group:
        name: "{{ user_group }}"
        state: present
    - name: Create user
      become: true
      ansible.builtin.user:
        name: "{{ user_name }}"
        group: "{{ user_group }}"
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa
      register: ssh_key_info
    - name: Install JDK
      become: true
      ansible.builtin.apt:
        name: "{{ java_packages }}"
        state: present
        update_cache: yes

- name: Get Jenkins master installed
  hosts: jenkins_masters
  tasks:
    - name: Add jenkins key
      become: true
      ansible.builtin.apt_key:
        url:  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add jenkins repo
      become: true
      ansible.builtin.apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: Install Jenkins and requirements
      become: true
      ansible.builtin.apt:
        name:
          - jenkins
          - git
        state: present

    - name: Start jenkins service
      become: true
      ansible.builtin.service:
        name: jenkins
        state: started

    - name: Enable jenkins to start at boot time
      become: true
      ansible.builtin.service:
        name: jenkins
        enabled: true

- name: Install docker and pip for jenkins agent
  hosts: jenkins_agents
  become: true
  tasks:
    - name: Create agent_dir
      ansible.builtin.file:
        path: "{{ jenkins_agent_dir }}"
        state: directory
        owner: "{{ jenkins_user_name }}"
        group: "{{ jenkins_user_group }}"
        mode: "0777"

    - name: Install dependencies via apt
      ansible.builtin.apt:
        name:
          - acl
          - ca-certificates
          - curl
          - gnupg
          - unzip

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's APT repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker and required
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - python3-pip
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: user
        append: yes
        groups: docker
    - name: Reset ssh connection to allow user changes to affect ansible user
      ansible.builtin.meta:
        reset_connection

- name: Install python packages
  hosts: jenkins_agents
  become_user: "{{ jenkins_user_name }}"
  tasks:
    - name: Install multi python packages with version specifiers
      ansible.builtin.pip:
        name:
          - ansible
          - molecule
          - molecule_docker
          - molecule_podman
    - name: Add local to PATH
      ansible.builtin.lineinfile:
        dest: ~/.bashrc
        regexp: export PATH=$PATH:/home/jenkins/.local/bin
        line: export PATH=$PATH:/home/jenkins/.local/bin

